name: NUBER_EATS_BACKEND_CI_CD
env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_CONTAINER: nuber-eats-backend

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
    steps:
      - name: Generate Environment Variables File for Test
        run: |
          echo "DB_HOST=$DB_HOST" >> .env.test
          echo "DB_NAME=$DB_NAME" >> .env.test
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env.test
          echo "DB_PORT=$DB_PORT" >> .env.test
          echo "DB_USERNAME=$DB_USERNAME" >> .env.test
          echo "MAILGUN_API_KEY=$MAILGUN_API_KEY" >> .env.test
          echo "MAILGUN_DOMAIN_NAME=$MAILGUN_DOMAIN_NAME" >> .env.test
          echo "MAILGUN_FROM_EMAIL=$MAILGUN_FROM_EMAIL" >> .env.test
          echo "PRIVATE_KEY=$PRIVATE_KEY" >> .env.test
          echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" >> .env.test
          echo "AWS_SECRET_ACESS_KEY=$AWS_SECRET_ACESS_KEY" >> .env.test
        env:
          DB_HOST: 'localhost'
          DB_NAME: 'postgres'
          DB_PASSWORD: 'postgres'
          DB_PORT: 5432
          DB_USERNAME: 'postgres'
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN_NAME: ${{ secrets.MAILGUN_DOMAIN_NAME }}
          MAILGUN_FROM_EMAIL: ${{ secrets.MAILGUN_FROM_EMAIL }}
          PRIVATE_KEY: '1111'
          AWS_ACCESS_KEY: '1111'
          AWS_SECRET_ACESS_KEY: '1111'

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install
      - run: npm run test:cov
      - run: npm run test:e2e

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Generate Environment Variables File for Production
        run: |
          echo "DB_HOST=$DB_HOST" >> .env.prod
          echo "DB_NAME=$DB_NAME" >> .env.prod
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env.prod
          echo "DB_PORT=$DB_PORT" >> .env.prod
          echo "DB_USERNAME=$DB_USERNAME" >> .env.prod
          echo "MAILGUN_API_KEY=$MAILGUN_API_KEY" >> .env.prod
          echo "MAILGUN_DOMAIN_NAME=$MAILGUN_DOMAIN_NAME" >> .env.prod
          echo "MAILGUN_FROM_EMAIL=$MAILGUN_FROM_EMAIL" >> .env.prod
          echo "PRIVATE_KEY=$PRIVATE_KEY" >> .env.prod
          echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" >> .env.prod
          echo "AWS_SECRET_ACESS_KEY=$AWS_SECRET_ACESS_KEY" >> .env.prod
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN_NAME: ${{ secrets.MAILGUN_DOMAIN_NAME }}
          MAILGUN_FROM_EMAIL: ${{ secrets.MAILGUN_FROM_EMAIL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACESS_KEY: ${{ secrets.AWS_SECRET_ACESS_KEY }}

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up docker build
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CI_CD_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_CD_TOKEN }}
      - name: Run docker
        run: |
          docker stop ${{ env.DOCKER_CONTAINER }} && docker rm ${{ env.DOCKER_CONTAINER }} && docker rmi ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest 
          docker run -d -p 4000:4000 --name ${{ env.DOCKER_CONTAINER }} --restart always ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
